name: Build
on:
  push:
    branches:
      - ['main', 'explore' ]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image: 
          - "swift:5.9.0"
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
        with:
          clean: true
          submodules: recursive
      - name: Build
        run: |
          rm -fr .build | echo "Removed build folder"
          swift build -c release --target RHVoice
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-build
          path: .build/release/